name: release
on: workflow_dispatch
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86_64-linux
            target: x86_64-unknown-linux-gnu
          - platform: aarch64-linux
            target: aarch64-unknown-linux-gnu
            setup: sudo ln -s /usr/bin/aarch64-linux-gnu-strip /usr/local/bin/strip
          - platform: x86_64-darwin
            target: x86_64-apple-darwin
            setup: sudo ln -s /opt/osxcross/target/bin/x86_64-apple-darwin-strip /usr/local/bin/strip
          - platform: arm64-darwin
            target: aarch64-apple-darwin
            setup: sudo ln -s /opt/osxcross/target/bin/aarch64-apple-darwin-strip /usr/local/bin/strip
          # - platform: x64-mingw-ucrt
          #   target: x86_64-pc-windows-gnu
          #   setup: sudo ln -s /usr/bin/x86_64-w64-mingw32-strip /usr/local/bin/strip
          # - platform: x64-mingw32
          #   target: x86_64-pc-windows-gnu
          #   setup: sudo ln -s /usr/bin/x86_64-w64-mingw32-strip /usr/local/bin/strip
    runs-on: ubuntu-latest
    name: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cargo install --locked --git https://github.com/ankane/cargo-3pl
          git clone https://github.com/ankane/3pl-source.git
          cargo 3pl --target ${{ matrix.target }} --require-files --source 3pl-source > LICENSE-THIRD-PARTY.txt
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - uses: oxidize-rb/cross-gem-action@v7
        with:
          platform: ${{ matrix.platform }}
          version: latest
          ruby-versions: "3.2,3.1,3.0,2.7"
          setup: |
            bundle install
            ${{ matrix.setup }}
